#!/usr/bin/env node
/**
 * Single source of truth for all deployment-host security-header files.
 *
 * Reads the CSP from src/core/util/csp.ts (as plain text) and emits:
 *   - public/_headers      (Cloudflare Pages / Netlify)
 *   - vercel.json          (Vercel)
 *   - render.yaml          (Render)
 *   - fly.toml             (Fly.io)
 *   - railway.json         (Railway)
 *
 * Run after `next build` so the CSP hashes can be updated (F2).
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

const ROOT = resolve(process.cwd())

const CSP_SOURCE = resolve(ROOT, 'src/core/util/csp.ts')
const cspMatch = readFileSync(CSP_SOURCE, 'utf8').match(/CROW_CSP\s*=\s*([\s\S]*?)\.join\('([^']+)'\)/)

let CROW_CSP
if (cspMatch) {
  const delimiter = cspMatch[2]
  const source = cspMatch[1].replace(/\n/g, '').replace(/\s+/g, ' ')
  const parts = eval(source)
  CROW_CSP = parts.join(delimiter)
} else {
  // Fallback if the source shape changes; keep in sync with csp.ts
  CROW_CSP = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src wss: https:; font-src 'self'; manifest-src 'self'; worker-src 'self'; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'none';"
}

const commonHeaders = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'no-referrer',
  'Permissions-Policy': 'camera=(self), microphone=(self), geolocation=(self)',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'Content-Security-Policy': CROW_CSP,
}

function headersBlock(headers) {
  return Object.entries(headers)
    .map(([k, v]) => `  ${k}: ${v}`)
    .join('\n')
}

// public/_headers (Cloudflare Pages / Netlify)
writeFileSync(
  resolve(ROOT, 'public/_headers'),
  `# Auto-generated by scripts/gen-headers.mjs — do not edit manually.
/*
${headersBlock(commonHeaders)}
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: camera=(self), microphone=(self), geolocation=(self)
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Content-Security-Policy: ${CROW_CSP}

/_next/static/*
  Cache-Control: public, max-age=31536000, immutable
`,
)

// vercel.json
writeFileSync(
  resolve(ROOT, 'vercel.json'),
  JSON.stringify(
    {
      headers: [
        {
          source: '/(.*)',
          headers: Object.entries(commonHeaders).map(([key, value]) => ({ key, value })),
        },
      ],
    },
    null,
    2,
  ) + '\n',
)

// render.yaml
writeFileSync(
  resolve(ROOT, 'render.yaml'),
  `# Auto-generated by scripts/gen-headers.mjs — do not edit manually.
previews:
  generate: false
services:
  - type: static
    name: crow
    buildCommand: npm ci && npm run generate:icons && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
${Object.entries(commonHeaders)
  .map(([k, v]) => `        - key: ${k}\n          value: "${v}"`)
  .join('\n')}
`,
)

// fly.toml
writeFileSync(
  resolve(ROOT, 'fly.toml'),
  `# Auto-generated by scripts/gen-headers.mjs — do not edit manually.
# Security headers are enforced by nginx.conf inside the Docker image.
app = 'crow'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  internal_port = 8080
  protocol = 'tcp'

  [[services.ports]]
    handlers = ['http']
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

  [services.http_checks]
    path = '/'
    interval = '10s'
    timeout = '2s'
`,
)

// railway.json
writeFileSync(
  resolve(ROOT, 'railway.json'),
  JSON.stringify(
    {
      $schema: 'https://railway.app/railway.schema.json',
      build: {
        builder: 'DOCKERFILE',
        dockerfilePath: 'Dockerfile',
      },
      deploy: {
        restartPolicyType: 'ON_FAILURE',
        restartPolicyMaxRetries: 10,
      },
      note: 'Security headers are enforced by nginx.conf inside the Docker image.',
    },
    null,
    2,
  ) + '\n',
)

console.log('Generated host header/config files from src/core/util/csp.ts')
